// #include <AMReX_MultiFab.H>
// #include <AMReX_REAL.H>

// namespace Solver {
//     using MF = typename amrex::MultiFab;
//     using MFSet = MultiFabSet;
//     using FAB = amrex::FArrayBox;
//     using RT  = amrex::Real;
//     using BCType = amrex::LinOpBCType;
//     using BCMode    = amrex::LinOpEnumType::BCMode;
//     using StateMode = amrex::LinOpEnumType::StateMode;
//     using Location  = amrex::LinOpEnumType::Location;
//     using BottomSolver = amrex::BottomSolver;
// }