#!/usr/bin/env python3

# Copyright 2017-2020 Andrew Myers, Axel Huebl, Burlen Loring
# Maxence Thevenet, Remi Lehe
#
# This file is part of WarpX.
#
# License: BSD-3-Clause-LBNL

# -*- coding: utf-8 -*-
#
# WarpX documentation build configuration file, created by
# sphinx-quickstart on Tue Mar  7 22:08:26 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import json
import logging
import os
import subprocess
import sys
import urllib.request

import pybtex.plugin
import sphinx_rtd_theme  # noqa
from pybtex.style.formatting.unsrt import Style as UnsrtStyle

# Heirachy of requirements:
# import pybtex
# import pybtex_docutils
# import sphinxcontrib.bibtex

import pybtex.style.template as template
import pybtex.richtext as richtext
from pybtex.richtext import Text


module_path = os.path.dirname(os.path.abspath(__file__))
checksum_path = os.path.join(module_path, "../../Regression/Checksum")
sys.path.insert(0, checksum_path)


def download_with_headers(url, filename):
    """Download a file with proper User-Agent header to avoid 403 errors."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "WarpX-docs-builder"})
        with urllib.request.urlopen(req) as response:
            with open(filename, "wb") as f:
                f.write(response.read())
    except Exception as e:
        print(f"Could not download {filename} from {url}: {e}")
        print("Continuing build without cross-reference file...")


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
    "sphinx_design",
    "breathe",
    "sphinxcontrib.bibtex",
    "sphinxcontrib.googleanalytics",
]

# Google Analytics
googleanalytics_id = "G-QZGY5060MZ"
googleanalytics_enabled = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# Relative path to bibliography file, bibliography style
bibtex_bibfiles = ["refs.bib"]


# An brief introduction to custom BibTex formatting can be found in the Sphinx documentation:
# https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#bibtex-custom-formatting
#
# More details can be gleaned from looking at the pybtex dist-package files.
# Some examples include the following:
# BaseStyle class in pybtex/style/formatting/__init__.py
# UnsrtStyle class in pybtex/style/formating/unsrt.py
class WarpXBibStyle(UnsrtStyle):
    # This option makes the family name, i.e, "last" name, of an author to appear first.
    # default_name_style = 'lastfirst'

    def __init__(self, *args, **kwargs):
        # This option makes the given names of an author abbreviated to just initials.
        # Example: "Jean-Luc" becomes "J.-L."
        # Set 'abbreviate_names' to True before calling the superclass (BaseStyle class) initializer
        kwargs["abbreviate_names"] = True
        super().__init__(*args, **kwargs)

    def format_web_refs(self, e):
        # print("")
        # print("format_web_refs: start")
        try:
            result = super().format_web_refs(e)
            # print("  format_web_refs: success")
            # print(f"  format_web_refs: result = {result}")
            return result
        except Exception as exception:
            print("")
            print(f"  format_web_refs: print: Exception: {exception}")
            print("")
            logging.warning(f"  format_web_refs: logging.warrning: Exception: {exception}")
            raise exception
        # finally:
        #     print("format_web_refs: end")

    # Override
    def format_pubmed(self, e):
        # print("\nformat_pubmed: start")
        return format_href_fixed(
            prefix1='https://www.ncbi.nlm.nih.gov/pubmed/',
            prefix2='PMID:',
            field_name='pubmed',
        )

    # Override
    def format_doi(self, e):
        # print("\nformat_doi: start")
        try:
            return format_href_fixed(
                prefix1='https://doi.org/',
                prefix2='doi:',
                field_name='doi',
            )
        except Exception as exception:
            print("")
            print(f"  format_doi: print: Exception: {exception}")
            print("")
            logging.warning(f"  format_doi: logging.warrning: Exception: {exception}")
            return super().format_doi(e)

    def format_eprint(self, e):
        # based on urlbst format.eprint
        # print("\nformat_eprint: start")
        return format_href_fixed(
            prefix1='https://arxiv.org/abs/',
            prefix2='arXiv:',
            field_name='eprint',
        )

def format_href_fixed(
    prefix1: str,
    prefix2: str,
    field_name: str,
) -> template.Node:
    # node_raw = template.field(field_key, raw=True)
    # node1 = removeprefix_from_node(prefix=prefix1, node=node_raw)
    # node_fixed = removeprefix_from_node(prefix=prefix2, node=node1)

    def _fix_text(text: Text) -> Text:
        old_text = str(text)
        try:
            # print(f"\n_fix_text: start, text = {text}")
            text = removeprefix_from_Text(text, prefix=prefix1)
            text = removeprefix_from_Text(text, prefix=prefix2)
            text = removeprefix_from_Text(text, prefix=prefix1)
            text = removeprefix_from_Text(text, prefix=prefix2)
        except Exception as exception:
            print(f"  _fix_text: print: Exception {exception}")
            logging.warning(f"  _fix_text: logging.warning: Exception {exception}")
            text = Text(old_text)
            raise exception
        return text

    # node_fixed = template.field(field_name, apply_func=_fix_text, raw=True)
    # node1 = template.join[prefix1, node_fixed]
    # node2 = template.join[prefix2, node_fixed]

    def _remove_both_prefixes(str_: str):
        result = str_
        result = result.removeprefix(prefix1)
        result = result.removeprefix(prefix2)
        result = result.removeprefix(prefix1)
        result = result.removeprefix(prefix2)
        return result

    def _add_prefix(text: Text, prefix: str) -> Text:
        field_text_str = str(text)
        if field_text_str.startswith('https') and prefix.startswith('https'):
            # Defer to text
            result = text
        else:
            field_text_fixed_str = _remove_both_prefixes(field_text_str)
            result = Text(prefix + field_text_fixed_str)
        return result

    def _join_prefix_1(text: Text) -> Text:
        return _add_prefix(text, prefix1)

    def _join_prefix_2(text: Text) -> Text:
        return _add_prefix(text, prefix2)

    node1 = template.field(field_name, apply_func=_join_prefix_1, raw=True)
    node2 = template.field(field_name, apply_func=_join_prefix_2, raw=True)


    result = template.href[node1, node2]
    return result

# `@template.node`` decorator is defined as
# def node(f: Callable):
#     return Node(f.__name__, f)
# where `f`` is a function that outputs richtext.Text

# It is called in `Node.format_data`:
# def format_data(self, data):
#     return self.f(self.children, data, *self.args, **self.kwargs)
#
# Therefore, the function `f` must have the signature:
# f(children, data, *args, **kwargs) -> Text

def removeprefix_from_Text(txt: richtext.Text, prefix: str) -> richtext.Text:
    result = txt
    if prefix:
        try:
            prefix_str = str(prefix)
            txt_str = str(txt)
            txt_str_removed = txt_str.removeprefix(prefix_str)
            if txt_str_removed != txt_str:
                result = richtext.Text(txt_str_removed)
                print("")
                print("removeprefix_from_Text:")
                print(f"  text = {txt}")
                print(f"  prefix='{prefix}'")
                print(f"  result = '{result}'")
        except Exception as e:
            print("")
            print(f"removeprefix_from_Text('{txt}', prefix='{prefix}'):")
            print(f"  Exception: {e}")
            logging.warning(e)
    return result

@template.node
def _removeprefix_from_node(
    children,
    data,
    node: template.Node,
    prefix: str,
) -> richtext.Text:
    txt = node[children].format_data(data)
    result = removeprefix_from_Text(txt, prefix=prefix)
    return result

def removeprefix_from_node(
    node: template.Node,
    prefix: str
) -> template.Node:
    return _removeprefix_from_node(node=node, prefix=prefix)

@template.node
def join_avoid_redundant_prefix(
    children,
    data,
    *args,
    **kwargs
) -> richtext.Text:

    join_node: template.Node
    result: richtext.Text
    extra_text: richtext.Text

    join_node = template.join(*args, **kwargs)
    result = join_node[children].format_data(data)

    try:
        child0 = children[0]
        if child0:
            prefix = str(child0)
            extra_text = join_node[children[1:]].format_data(data)
            extra_text = removeprefix_from_Text(extra_text, prefix=prefix)
            new_text = richtext.Text(prefix + str(extra_text))
        if str(new_text) != str(result):
            old_result_str = str(result)
            result = new_text
            print(f"\njoin_remove_redundant_prefix:\n  removing extra prefix='{prefix}' in '{old_result_str}'\n  result = '{result}'")
    except Exception as e:
        print(f"\njoin_remove_redundant_prefix:\n  Exception: {e}")
        logging.warning(e)

    return result


pybtex.plugin.register_plugin("pybtex.style.formatting", "warpxbibstyle", WarpXBibStyle)

bibtex_default_style = "warpxbibstyle"

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "WarpX"
copyright = "2017-2021, WarpX collaboration"
author = "WarpX collaboration"

# Parse WarpX version information
dependencies_file = "../../dependencies.json"
with open(dependencies_file, "r") as file:
    dependencies_data = json.load(file)
warpx_version = dependencies_data.get("version_warpx")

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = warpx_version
# The full version, including alpha/beta/rc tags.
release = warpx_version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
html_logo = "_static/WarpX_Logo.png"

numfig = True
math_eqref_format = "{number}"
numfig_format = {
    "figure": "Fig. %s",
    "table": "Table %s",
    "code-block": "Listing %s",
    "section": "Section %s",
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_css_files = [
    "custom.css",
]

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "WarpXdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "WarpX.tex", "WarpX Documentation", "WarpX collaboration", "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "warpx", "WarpX Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "WarpX",
        "WarpX Documentation",
        author,
        "WarpX",
        "WarpX is an advanced electromagnetic Particle-In-Cell code.",
        "Miscellaneous",
    ),
]


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"https://amrex-codes.github.io/": None}

# Setup the breathe extension
breathe_projects = {"WarpX": "../doxyxml/"}
breathe_default_project = "WarpX"

# Tell sphinx what the primary language being documented is.
primary_domain = "cpp"
# Tell sphinx what the pygments highlight language should be.
highlight_language = "cpp"

# Download AMReX & openPMD-api Doxygen Tagfile to interlink Doxygen docs
download_with_headers(
    url="https://amrex-codes.github.io/amrex/docs_xml/doxygen/amrex-doxygen-web.tag.xml",
    filename="../amrex-doxygen-web.tag.xml",
)
download_with_headers(
    url="https://openpmd-api.readthedocs.io/en/latest/_static/doxyhtml/openpmd-api-doxygen-web.tag.xml",
    filename="../openpmd-api-doxygen-web.tag.xml",
)

# Build Doxygen
subprocess.call(
    "cd ../; doxygen;"
    "mkdir -p source/_static;"
    "cp -r doxyhtml source/_static/;"
    "cp warpx-doxygen-web.tag.xml source/_static/doxyhtml/",
    shell=True,
)

suppress_warnings = ["bibtex.duplicate_label"]

# def format_href_node(
#     children,
#     data,
#     prefix1: str,
#     prefix2: str,
#     field_name: str,
# ) -> Text:

#     # if field_text.startswith('https'):
#     #     if prefix1.startswith('https'):
#     #         node1 =

#     @template.node
#     def node1(children, data) -> Text:
#         assert not children
#         field_text: Text = template.field(field_name, raw=False).format_data(data)
#         field_text_str: str = str(field_text)
#         result = field_text

#         if field_text_str.startswith('https') and prefix1.startswith('https'):
#             return field_text
#         else:
#             result_str = field_text_str.removeprefix(prefix1)
#             result_str = field_text_str.removeprefix(prefix2)
#             result_str = field_text_str.removeprefix(prefix1)
#             result_str = field_text_str.removeprefix(prefix2)
#             result = Text(prefix1 + result_str)
#         return result

#     result = template.href[node1, node2]
#     return result
